const { fontFamily } = require("tailwindcss/defaultTheme");
import type { Config } from "tailwindcss";

const config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        raleway: ["var(--font-raleway)", ...fontFamily.sans],
      },
      colors: {
        admin: {
          primary: "#3A47AB",
          secondary: "#4A56DB",
          sidebarBackground: "#18202F",
          subMenuBackground: "#323946",
          sidebarBorder: "#313131",
          inputBackground: "#F0F0F7",
          bodyBackground: "#F0F0F7",
          customGray: "#646363",
          sidebarIcon: "#ffffff",
          inputLabels: "#0B0F18",
          commonBlack: "#0B0F18",
          lightPrimary: "#EEF2FF",
          buttonLink: "#276d97",
          lightBlue: "#00BCD4",
          lightBlueHex: "#00BCD4",
          hoverBlue: "#00BCD4",
          tableHeader: "#F5F6FA;",
          coolGray: "#2B3740",
          background: "#C9CED4",
          tertiary: "#2B3740",
          lightGray: "#E5E5E5",
          font: "#2B3740",
          gray1: "#DDDDDD",
          gray2: "#BBBBBB",
          gray3: "#878793",
          gray4: "#727272",
          gray5: "#707070,",
          gray6: "#3A3952",
          gray7: "#F9FAFB",
          textColor: "#111827",
          inputBorder: "#D1D5DB",
          buttonColor: "#3A3952",
          black: "#000000",
          green: "#07BF6F",
          charcoal: "#353940",
          purple: "#7F43F9",
          gradientBlue: "#39E4FB",
          darkPurple: "#312D36",
          offWhite: "#EBEBED",
          iconColor: "#6C6CB9",
          orange: "#EC4E20",
          blue: "#357FFA",
          indigo: "#4F46E5",
          disabled: "#e2e8f0",
          bgBlue: "#bde4ff",
          grayText: "#6B7280",
          tagBg: "#ffffff14",
          lightYellow: "#FEF3C7",
          darkYellow: "#92400E",
          lightGreen: "#D1FAE5",
          darkGreen: "#065F46",
          lightRed: "#FEE2E2",
          darkRed: "#991B1B",
          lightIndigo: "#EEF2FF",
          bronze: "#CD7F32",
          gold: "#ffd700",
          platinum: "#8F65EE",
          diamond: "#49D261",
          silver: "#808080",
          ggg: "#f3f4f7",
          pink: "#FFC0CB",
          teal: "teal",
          cus_pink: "#AA336A",
          subMenuPopUpBackground: "#18202F",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderColor: {
        bronze: "#CD7F32",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      theme: {
        screens: {
          ssm: "400px",
          xsm: "450px",
          sm: "640px",
          md: "768px",
          cu_tab: "769px",
          lg: "1024px",
          xl: "1280px",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;

export default config;
