export const metadata = {
  title: 'Forgot Password | Admin',
  description: 'Generated by create next app',
};
interface Props {
  children: React.ReactNode;
}

export default function Layout({ children }: Props) {
  return <>{children}</>;
}
