import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' });

export const metadata: Metadata = {
  title: 'Admin Panel',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-raleway antialiased',
          raleway.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
