export const metadata = {
  title: 'Login | Admin',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return <>{children}</>;
}
