export const metadata = {
  title: 'Users | Admin',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
