export const metadata = {
  title: 'Users | Admin',
  description: 'Generated by create next app',
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
